const map=L.map('map').setView([-7.25,112.75],11);
// Basemap baru: Esri World Street Map. UI/UX dan seluruh fungsi WebGIS dipertahankan.
L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri — Source: Esri, DeLorme, NAVTEQ, USGS, and other contributors'}).addTo(map);
map.pm.addControls({position:'topleft',drawPolygon:true,drawRectangle:true,drawCircle:false,drawMarker:false,drawCircleMarker:false,drawPolyline:false,editMode:true,dragMode:false,cutPolygon:false,removalMode:true});
let aoiLayer=null,resultLayer=null,uploadedLayer=null,lastRequest=null;
map.on('pm:create',e=>{if(aoiLayer)map.removeLayer(aoiLayer);aoiLayer=e.layer;aoiLayer.addTo(map);document.getElementById('status').textContent='AOI ready. Click RUN ANALYSIS.';});
const $=id=>document.getElementById(id);
$('clear').onclick=()=>{if(aoiLayer)map.removeLayer(aoiLayer);if(resultLayer)map.removeLayer(resultLayer);if(uploadedLayer)map.removeLayer(uploadedLayer);aoiLayer=null;resultLayer=null;uploadedLayer=null;lastRequest=null;$('results').hidden=true;$('status').textContent='Draw an AOI on the map.';$('upload-status').textContent='Upload raster GeoTIFF untuk melihat metadata dan preview.';};
function requestBody(){return {module:$('module').value,variable:$('variable').value,aoi:aoiLayer.toGeoJSON().geometry,start_date:$('start').value,end_date:$('end').value,aggregation:$('aggregation').value};}
$('run').onclick=async()=>{if(!aoiLayer){$('status').textContent='Please draw an AOI first.';return}const start=$('start').value,end=$('end').value;if(!start||!end){$('status').textContent='Start and end dates are required.';return}if(end<=start){$('status').textContent='End date must be after start date.';return}const body=requestBody();lastRequest=body;$('status').textContent='Processing Sentinel-5P CO in Google Earth Engine…';$('run').disabled=true;try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Analysis failed');$('value').textContent=Number(data.value).toExponential(4);$('unit').textContent=data.unit;$('images').textContent=data.image_count;$('dates').textContent=`${data.start_date} → ${data.end_date}`;$('note').textContent=data.note;$('results').hidden=false;if(resultLayer)map.removeLayer(resultLayer);if(data.map?.tile_url)resultLayer=L.tileLayer(data.map.tile_url,{opacity:.65}).addTo(map);$('status').textContent='Analysis complete.';}catch(err){$('status').textContent=err.message}finally{$('run').disabled=false}};
$('download-tif').onclick=async()=>{if(!lastRequest){$('status').textContent='Run an analysis first.';return}$('status').textContent='Preparing GeoTIFF export…';try{const r=await fetch('/api/export/geotiff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lastRequest)});const d=await r.json();if(!r.ok)throw new Error(d.detail||'GeoTIFF export failed');window.open(d.download_url,'_blank');$('status').textContent='GeoTIFF download link opened.';}catch(e){$('status').textContent=e.message}};
$('download-pdf').onclick=async()=>{if(!lastRequest){$('status').textContent='Run an analysis first.';return}$('status').textContent='Generating PDF report…';try{const r=await fetch('/api/report/pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lastRequest)});if(!r.ok){const d=await r.json();throw new Error(d.detail||'PDF generation failed')}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`CO_report_${lastRequest.start_date}_${lastRequest.end_date}.pdf`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);$('status').textContent='PDF report downloaded.';}catch(e){$('status').textContent=e.message}};
$('upload').onclick=async()=>{const file=$('geotiff').files[0];if(!file){$('upload-status').textContent='Choose a .tif or .tiff file first.';return}const fd=new FormData();fd.append('file',file);$('upload').disabled=true;$('upload-status').textContent='Uploading GeoTIFF…';try{const r=await fetch('/api/upload/geotiff',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Upload failed');$('upload-status').innerHTML=`<b>${d.filename}</b><br>CRS: ${d.crs}<br>Size: ${d.width} × ${d.height} · Bands: ${d.bands}<br><a href="${d.preview_url}" target="_blank">Open preview</a> · <a href="/api/upload/geotiff/${d.id}/download">Download original</a>`;if(uploadedLayer)map.removeLayer(uploadedLayer);const bounds=[[d.bounds[1],d.bounds[0]],[d.bounds[3],d.bounds[2]]];uploadedLayer=L.imageOverlay(d.preview_url,bounds,{opacity:.65}).addTo(map);map.fitBounds(bounds);$('status').textContent='GeoTIFF uploaded and displayed.';}catch(e){$('upload-status').textContent=e.message}finally{$('upload').disabled=false}};
const infoToggle=$('info-toggle'),infoPanel=$('info-panel'),infoClose=$('info-close');
function setInfo(open){infoPanel.hidden=!open;infoToggle.setAttribute('aria-expanded',String(open));}
infoToggle.addEventListener('click',()=>setInfo(infoPanel.hidden));infoClose.addEventListener('click',()=>setInfo(false));document.addEventListener('keydown',e=>{if(e.key==='Escape')setInfo(false)});
