const map=L.map('map').setView([-7.25,112.75],11);
L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri — Source: Esri, DeLorme, NAVTEQ, USGS, and other contributors'}).addTo(map);
map.pm.addControls({position:'topleft',drawPolygon:true,drawRectangle:true,drawCircle:false,drawMarker:false,drawCircleMarker:false,drawPolyline:false,editMode:true,dragMode:false,cutPolygon:false,removalMode:true});
let aoiLayer=null,aoiGeometry=null,resultLayer=null,lastRequest=null,chartInstance=null,aoiVisible=true,resultVisible=true,chartToken=0,legendControl=null,pdfUrl=null;
const $=id=>document.getElementById(id);
const cfg={SO2:{name:'Sulfur Dioxide (SO₂)',unit:'µg/m³',min:0,max:100,colors:['#2C115F','#4C2A85','#2F6DB0','#2BA8B8','#65C9A4','#C7E77B','#FDE68A','#F59E0B','#DC2626']},NO2:{name:'Nitrogen Dioxide (NO₂)',unit:'µg/m³',min:0,max:100,colors:['#081D58','#225EA8','#1D91C0','#41B6C4','#7FCDBB','#C7E9B4','#EDF8B1','#FEC44F','#F03B20']},CO:{name:'Carbon Monoxide (CO)',unit:'µg/m³',min:0,max:100,colors:['#2E1065','#5B21B6','#9333EA','#DB2777','#F43F5E','#FB7185','#FDBA74','#FDE68A','#FEF3C7']},CH4:{name:'Methane (CH₄)',unit:'ppm',min:1.8,max:1.9,colors:['#064E3B','#047857','#059669','#34D399','#A7F3D0','#FEF08A','#FBBF24','#F97316','#B91C1C']}};
function errorMessage(detail,fallback='Request failed'){if(detail instanceof Error&&detail.message)return detail.message;if(typeof detail==='string'&&detail.trim())return detail;if(detail&&typeof detail==='object'){if(typeof detail.message==='string'&&detail.message.trim())return detail.message;if(typeof detail.error==='string'&&detail.error.trim())return detail.error;try{return JSON.stringify(detail)}catch(_){return fallback}}return fallback}
async function responseError(r,fallback){let d=null;try{d=await r.json()}catch(_){ }return new Error(errorMessage(d?.detail??d,`${fallback} (HTTP ${r.status})`))}
function setAOI(geometry,zoom=true){if(!geometry||!['Polygon','MultiPolygon'].includes(geometry.type))throw new Error('AOI must be a Polygon or MultiPolygon.');if(aoiLayer)map.removeLayer(aoiLayer);aoiGeometry=geometry;aoiVisible=true;aoiLayer=L.geoJSON({type:'Feature',properties:{},geometry},{style:{color:'#1687ff',weight:3,fillOpacity:.12}}).addTo(map);if(zoom)map.fitBounds(aoiLayer.getBounds(),{padding:[30,30]});$('toggle-aoi').textContent='HIDE AOI';$('toggle-aoi').disabled=false;$('status').textContent='AOI ready. Click RUN ANALYSIS.'}
map.on('pm:create',e=>{try{setAOI(e.layer.toGeoJSON().geometry)}catch(err){$('status').textContent=errorMessage(err.message,'Invalid AOI.')}});
function requestBody(){if(!aoiGeometry)throw new Error('Please draw an AOI or upload one first.');return{module:$('module').value,variable:$('variable').value,aoi:aoiGeometry,start_date:$('start').value,end_date:$('end').value,aggregation:$('aggregation').value,interval:$('interval').value}}
function validateDates(){const start=$('start').value,end=$('end').value;if(!start||!end)return'Start and end dates are required.';if(end<start)return'End date must be on or after start date.';if((new Date(end)-new Date(start))/86400000>=366)return'Maximum analysis period is 365 days. Please select a shorter period.';return null}
function clearLegend(){if(legendControl){map.removeControl(legendControl);legendControl=null}}
function showLegend(variable){clearLegend();const c=cfg[variable];legendControl=L.control({position:'bottomright'});legendControl.onAdd=()=>{const div=L.DomUtil.create('div','analysis-legend');div.innerHTML=`<div class="legend-title">${c.name}</div><div class="legend-gradient" style="background:linear-gradient(to right,${c.colors.join(',')})"></div><div class="legend-scale"><span>${c.min} ${c.unit}</span><span>${c.max} ${c.unit}</span></div>`;return div};legendControl.addTo(map)}
function openChartLoading(request){$('chart-panel').hidden=false;$('chart-title').textContent=`${cfg[request.variable].name} time series`;$('chart-subtitle').textContent=`${$('aggregation').selectedOptions[0].text} over selected AOI · ${cfg[request.variable].unit}`;$('chart-period').textContent=`${request.start_date} → ${request.end_date}`;$('chart-method').textContent=`${$('aggregation').selectedOptions[0].text} · ${$('interval').selectedOptions[0].text}`;$('chart-loading').hidden=false;$('chart-empty').hidden=true;$('timeseries-chart').style.visibility='hidden'}
function closeChart(){$('chart-panel').hidden=true}
function drawChart(series,request){if(request!==lastRequest)return;const c=cfg[request.variable],labels=series.map(x=>x.date),values=series.map(x=>Number(x.value));$('chart-loading').hidden=true;$('chart-empty').hidden=values.length>0;$('chart-empty').textContent='No time-series data available for the selected period.';$('timeseries-chart').style.visibility=values.length?'visible':'hidden';if(chartInstance){chartInstance.destroy();chartInstance=null}if(!values.length)return;chartInstance=new Chart($('timeseries-chart'),{type:'line',data:{labels,datasets:[{label:`${request.variable} (${c.unit})`,data:values,tension:.25,pointRadius:2.5,pointHoverRadius:5,borderWidth:2,fill:true,backgroundColor:c.colors[4]+'2B',borderColor:c.colors[4]}]},options:{responsive:true,maintainAspectRatio:false,animation:{duration:250},interaction:{mode:'index',intersect:false},plugins:{legend:{labels:{color:'#d9e4f3'}},tooltip:{callbacks:{label:x=>` ${Number(x.raw).toExponential(4)} ${c.unit}`}}},scales:{x:{ticks:{color:'#8fa2bc',maxRotation:0},grid:{color:'rgba(255,255,255,.07)'}},y:{ticks:{color:'#8fa2bc',callback:x=>Number(x).toExponential(2)},grid:{color:'rgba(255,255,255,.07)'}}}}});requestAnimationFrame(()=>chartInstance?.resize())}
async function loadChart(request=lastRequest){if(!request)return;const token=++chartToken;openChartLoading(request);try{const r=await fetch('/api/chart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request),cache:'no-store'});if(!r.ok)throw await responseError(r,'Time series failed');const d=await r.json();if(token!==chartToken||request!==lastRequest)return;drawChart(d.series||[],request)}catch(e){if(token!==chartToken)return;$('chart-loading').hidden=true;$('timeseries-chart').style.visibility='hidden';$('chart-empty').textContent=errorMessage(e,'Time series failed');$('chart-empty').hidden=false}}
function closePdfPreview(){if(pdfUrl){URL.revokeObjectURL(pdfUrl);pdfUrl=null}$('pdf-preview').hidden=true;$('pdf-frame').src='about:blank'}
async function previewPdf(){if(!lastRequest){$('status').textContent='Run an analysis first.';return}$('status').textContent='Preparing PDF preview…';$('download-pdf').disabled=true;try{const r=await fetch('/api/report/pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lastRequest),cache:'no-store'});if(!r.ok)throw await responseError(r,'PDF generation failed');const blob=await r.blob();if(!blob.size)throw new Error('The PDF response was empty.');if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl=URL.createObjectURL(blob);$('pdf-frame').src=pdfUrl;$('pdf-preview').hidden=false;$('status').textContent='PDF preview ready. Review it before downloading.'}catch(e){$('status').textContent=errorMessage(e,'PDF generation failed')}finally{$('download-pdf').disabled=false}}
function downloadPreviewedPdf(){if(!pdfUrl)return;$('status').textContent='Downloading reviewed PDF…';const a=document.createElement('a');a.href=pdfUrl;a.download=`${lastRequest.variable}_report_${lastRequest.start_date}_${lastRequest.end_date}.pdf`;document.body.appendChild(a);a.click();a.remove();$('status').textContent='PDF report downloaded.';closePdfPreview()}
$('run').onclick=async()=>{if(!aoiGeometry){$('status').textContent='Please draw an AOI or upload one first.';return}const validation=validateDates();if(validation){$('status').textContent=validation;return}let body;try{body=requestBody()}catch(err){$('status').textContent=errorMessage(err,'Invalid request');return}lastRequest=body;chartToken++;clearLegend();closePdfPreview();$('status').textContent=`Processing Sentinel-5P ${body.variable} in Google Earth Engine…`;$('run').disabled=true;$('results').hidden=true;openChartLoading(body);const chartPromise=loadChart(body);try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});if(!r.ok)throw await responseError(r,'Analysis failed');const data=await r.json();if(body!==lastRequest)return;$('value').textContent=Number(data.value).toExponential(4);$('unit').textContent=data.unit;$('images').textContent=data.image_count;$('dates').textContent=`${data.start_date} → ${data.end_date}`;$('note').textContent=data.note;$('severity').textContent=data.interpretation?.label||'Relative';$('results').hidden=false;if(resultLayer)map.removeLayer(resultLayer);if(data.map?.tile_url)resultLayer=L.tileLayer(data.map.tile_url,{opacity:.68}).addTo(map);resultVisible=true;$('toggle-result').textContent='HIDE ANALYSIS';$('toggle-result').disabled=!resultLayer;showLegend(body.variable);$('status').textContent='Analysis complete. Time series is loading…';await chartPromise;$('status').textContent='Analysis complete. Time series ready.'}catch(err){$('status').textContent=errorMessage(err,'Analysis failed');$('chart-loading').hidden=true;$('chart-empty').textContent=errorMessage(err,'Analysis failed');$('chart-empty').hidden=false}finally{$('run').disabled=false}};
$('variable').addEventListener('change',()=>{chartToken++;if(resultLayer){map.removeLayer(resultLayer);resultLayer=null}lastRequest=null;$('results').hidden=true;closeChart();clearLegend();$('toggle-result').disabled=true;$('toggle-result').textContent='SHOW ANALYSIS'});
$('open-chart').onclick=()=>{if(lastRequest)loadChart(lastRequest);else $('status').textContent='Run an analysis first.'};$('chart-close').onclick=closeChart;
$('toggle-aoi').onclick=()=>{if(!aoiLayer)return;if(aoiVisible){map.removeLayer(aoiLayer);aoiVisible=false;$('toggle-aoi').textContent='SHOW AOI'}else{aoiLayer.addTo(map);aoiVisible=true;$('toggle-aoi').textContent='HIDE AOI'}};
$('toggle-result').onclick=()=>{if(!resultLayer)return;if(resultVisible){map.removeLayer(resultLayer);resultVisible=false;$('toggle-result').textContent='SHOW ANALYSIS'}else{resultLayer.addTo(map);resultVisible=true;$('toggle-result').textContent='HIDE ANALYSIS'}};
$('download-tif').onclick=async()=>{if(!lastRequest){$('status').textContent='Run an analysis first.';return}$('status').textContent='Preparing GeoTIFF download…';$('download-tif').disabled=true;try{const r=await fetch('/api/export/geotiff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lastRequest),cache:'no-store'});if(!r.ok)throw await responseError(r,'GeoTIFF download failed');const blob=await r.blob();if(!blob.size)throw new Error('The GeoTIFF response was empty.');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${lastRequest.variable}_${lastRequest.start_date}_${lastRequest.end_date}.tif`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);$('status').textContent='GeoTIFF downloaded.'}catch(e){$('status').textContent=errorMessage(e,'GeoTIFF download failed')}finally{$('download-tif').disabled=false}};
$('download-pdf').onclick=previewPdf;$('pdf-close').onclick=closePdfPreview;$('pdf-cancel').onclick=closePdfPreview;$('pdf-download').onclick=downloadPreviewedPdf;
$('clear').onclick=()=>{chartToken++;clearLegend();closePdfPreview();if(aoiLayer)map.removeLayer(aoiLayer);if(resultLayer)map.removeLayer(resultLayer);aoiLayer=null;aoiGeometry=null;resultLayer=null;lastRequest=null;aoiVisible=true;resultVisible=true;$('results').hidden=true;closeChart();if(chartInstance){chartInstance.destroy();chartInstance=null}$('upload-status').textContent='';$('toggle-aoi').disabled=true;$('toggle-aoi').textContent='SHOW AOI';$('toggle-result').disabled=true;$('toggle-result').textContent='SHOW ANALYSIS';$('status').textContent='Draw an AOI or upload a Shapefile ZIP.'};
$('aoi-file').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;$('upload-status').textContent='Uploading and reading AOI…';$('status').textContent='Reading AOI file…';const form=new FormData();form.append('file',file);try{const r=await fetch('/api/upload/aoi',{method:'POST',body:form,cache:'no-store'});if(!r.ok)throw await responseError(r,'AOI upload failed');const d=await r.json();setAOI(d.geometry);$('upload-status').textContent=`Loaded ${d.feature_count||1} polygon feature(s)${d.source_epsg?` · EPSG:${d.source_epsg}`:''}.`}catch(err){const msg=errorMessage(err,'AOI upload failed');$('upload-status').textContent=msg;$('status').textContent=msg}finally{e.target.value=''}});
const infoToggle=$('info-toggle'),infoPanel=$('info-panel'),infoClose=$('info-close');function setInfo(open){infoPanel.hidden=!open;infoToggle.setAttribute('aria-expanded',String(open))}infoToggle.addEventListener('click',()=>setInfo(infoPanel.hidden));infoClose.addEventListener('click',()=>setInfo(false));
const welcome=$('welcome-modal');function closeWelcome(){welcome.classList.add('is-hidden')}$('welcome-close').onclick=closeWelcome;$('start-app').onclick=closeWelcome;document.addEventListener('keydown',e=>{if(e.key==='Escape'){setInfo(false);closeChart();closeWelcome();closePdfPreview()}});
